w3c/webappsec-referrer-policy

.travis.yml
index.html
index.src.html

@annevk @jeisinger @franziskuskiefer this is an attempt to address the comments regarding renaming "referrer" to "referrerpolicy" as discussed in https://github.com/w3c/webappsec/issues/409
This PR is migrating from one against the old repo: https://github.com/w3c/webappsec/pull/435
/cc @wooseok

Rename attribute delivery from referrer to referrerpolicy

---

index.html
index.src.html

@annevk @jeisinger as discussed in https://github.com/w3c/webappsec/pull/435 this is an attempt to specify what action is expected when UAs encounter rel=noreferrer and a referrerpolicy attribute on the same element.
The conservative approach is to be backwards-compatible and honor rel=noreferrer.
/cc @wooseok @franziskuskiefer

make rel=noreferrer take priority over referrerpolicy attribute

---

index.html
index.src.html

This makes it easier to deploy new policy values: older browsers will
ignore unknown referrer policy values instead of treating them as
"never". See issue #4.

Treat unknown referrer policy values as null

---

index.html
index.src.html

There is a use case for making an invalid value return null, so that older browsers ignore newer values that they don't recognize. But there isn't a use case for returning null for an empty referrer policy, so specify that empty should be treated as No Referrer.
This matches what I implemented in https://codereview.chromium.org/1454823004/
@jeisinger PTAL?

Specify that an empty token is No Referrer

---

index.html
index.src.html

@jeisinger @mikewest this specifies the simplest possible Referrer-Policy header, with the idea that we could extend the syntax later to be more complicated if necessary. Also an attempt to specify what happens when a Referrer-Policy header is received on a redirect response. What do you think?

Replace referrer directive with Referrer-Policy header

---

.travis.yml

The current Travis setup is broken: https://travis-ci.org/w3c/webappsec-referrer-policy/builds/103249519

Copy Travis config from CSP repo (MERGE FIRST!)

---

index.html
index.src.html

This cleans up the Fetch integration in the following ways:
- Integrate the handling of Referrer-Policy headers on redirects with
the HTTP-redirect fetch algorithm. This (I think) removes the need for
responses to have associated referrer policies, and is also more
precise/clean.
- Insert a TODO to define an HTML integration for the referrerpolicy
content attributes. This removes the need for handwavy handling of the
attribute when determining the Referer for a request.
- Use the request's referrer policy when determining the Referer for a
request (no need to consult the environment's policy because that is
now accounted for in Fetch as of
https://github.com/whatwg/fetch/pull/280). Issue 26

Rewrite Fetch integration, especially around redirects

---

index.html
index.src.html

This is the counterpart to https://github.com/whatwg/html/pull/1153, which removes the parts of the spec that are now defined in HTML: the content and IDL attributes on various elements, plus the `<meta http-equiv>` extension.
There is still much to do; I will open a separate issue detailing the plan.

Integrate with HTML, part 1 of n

---

index.html

@estark37 many apologies; I forgot to commit the changes to the output document in https://github.com/w3c/webappsec-referrer-policy/commit/ae3e8933125caa5f39eeadff235eeee49ac12ee1. A quick merge and `make publish` will fix the inconsistency.

Change "origin-only" to "origin"

---

index.src.html

That was the source of the typo discovered by @estark37 in
https://github.com/w3c/webappsec-referrer-policy/pull/19#discussion_r63733290

Remove a superfluous "any"

---

index.src.html

Except for "No Referrer", the existing policy states do not allow authors to use a policy that maintains the downgrade protection of the default referrer policy and also limit the amount of information that is leaked via the `Referer` header to just the origin.
This new policy state allows an author to maintain full referrer information for their internal pages while not leaking anything out to third-parties.
(I am planning on updating the privacy considerations section in a future commit.)

Introduce a "Same-Origin Only" policy state

---

index.html
index.src.html

This is the counterpart to https://github.com/whatwg/html/pull/1205, reflecting the Referrer Policy spec to no longer try to specify "implicit delivery". It also creates a dedicated section for the empty-string referrer policy.
This closes #30 and closes #32.

Integrate with HTML, part 2 of n

---

index.src.html

That was the source of the typo discovered by @estark37 in
https://github.com/w3c/webappsec-referrer-policy/pull/52/files/3bbd369b797abd3c51e4f7a3cb94f6349457ef12#r65738690

Add a missing "a"

---

index.html
index.src.html

This was discussed in #43. It doesn't necessarily help with #31, but is a good stage-setting for whatever we do there eventually...

Fix referrer calculation to not refer to "API referrer source"

---

index.html
index.src.html

The description of when a referrer policy is set on redirect referred to
a non-existent step in the HTTP-redirect fetch algorithm. The
corresponding Fetch change is in
https://github.com/whatwg/fetch/pull/335.
The section about when "Determine request's referrer" is called was also
inaccurate.

Update Integration with Fetch section

---

index.html
index.src.html

"Determine request's referrer" now uses the environment's global
object's associated Document instead of the active document of its
browsing context. Fixes https://github.com/w3c/webappsec-referrer-policy/issues/29.

Fix use of "active document" in determining referrer

---

index.html
index.src.html

By keeping the definition in REFERRER, adding new policy values requires
only changing one spec, instead of three.
Fixes #62

Copy referrer policy concept and enum from Fetch

---

index.html
index.src.html

As suggested in https://github.com/w3c/webappsec-referrer-policy/issues/53, instead of
using "Determine token's policy" to parse Referrer-Policy headers, we
can simply use the referrer policy definition. This also makes it more
explicit that legacy keywords are not supported in Referrer-Policy
headers.

Use referrer policy definition in parsing Referrer-Policy headers

---

index.html
index.src.html

The HTML meta element now translates legacy keywords into real referrer
policies, so this algorithm is no longer needed.
While removing a reference to it in "Unknown Policy Values", I also
clarified that this section applies to Document policies, not
'referrerpolicy' attributes.
Fixes #53, #46.

Remove "Determine policy for token"

---

index.html
index.src.html

/cc @estark37 @annevk @domenic

Add a section about CSS and referrers (#5)

---

index.html
index.src.html

Hopefully this will make specberus happy.

Undo change of shortname, and instead mark the spec as unlevelled

---

index.html
index.src.html

RFC6454 is effectively obsolete. Also clean up some references to Fetch.

Editorial: reference origin terms from the HTML Standard

---

index.html
index.src.html

This adds a couple examples for how to send multiple Referrer-Policy header
values in the section about falling back on unknown policy values.
Fixes https://github.com/w3c/webappsec-referrer-policy/issues/81

Add an example for multiple Referrer-Policy headers

---

index.html
index.src.html

@annevk pointed out in https://github.com/w3c/web-platform-tests/pull/5054#issuecomment-284664280 that when `policy-token` is defined as a collection of literals corresponding to the valid referrer policies, the browser should technically completely disregard a header of the form `Referrer-Policy: origin, blah`. Instead, we want the browser to ignore `blah` as an unknown policy value and fall back to `origin`.
So this PR relaxes the ABNF of the `Referrer-Policy` header to parse invalid policy values.

Relax ABNF for invalid policy tokens

---

index.html
index.src.html

This is similar to https://github.com/w3c/webappsec-csp/pull/206

Add a link to web-platform-tests to the top of the spec

---

index.html
index.src.html

In 8.3 > step 3 > "client" case > step 2 there is an invalid link to HTML definition of a creation URL (now existing at #concept-environment-creation-url) which this PR addresses.
Also, not sure why the generated index file has soooo many changes, I only touched the src file and ran bikeshed. Is this because bikeshed has been updated since the last commit to this spec or did I mess something up?
***
[Preview](https://s3.amazonaws.com/pr-preview/domfarolino/webappsec-referrer-policy/master.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webappsec-referrer-policy/8232912...domfarolino:65d5c52.html)

Fix HTML link: creation URL

---

index.html
index.src.html

***
<a href="https://pr-preview.s3.amazonaws.com/jeisinger/webappsec-referrer-policy/pull/117.html" title="Last updated on Oct 25, 2018, 8:59 AM GMT (58679ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/117/cd3894a...jeisinger:58679ac.html" title="Last updated on Oct 25, 2018, 8:59 AM GMT (58679ac)">Diff</a>

rel="noreferrer" is not supported for <link> elements

---

index.html
index.src.html

As @johnwilander requested in https://github.com/whatwg/fetch/pull/952#issuecomment-543219126.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/pull/127.html" title="Last updated on Oct 18, 2019, 8:56 AM UTC (3e2666d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/127/20aad3a...3e2666d.html" title="Last updated on Oct 18, 2019, 8:56 AM UTC (3e2666d)">Diff</a>

Codify user agent flexibility with regard to referrer values.

---

index.src.html

If the `referer` header's value is a URL with a length of more than 4k, strip it down to an origin.
Fixes https://github.com/whatwg/fetch/issues/903.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/pull/122.html" title="Last updated on Oct 21, 2019, 10:21 AM UTC (039ee88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/122/1a1f47b...039ee88.html" title="Last updated on Oct 21, 2019, 10:21 AM UTC (039ee88)">Diff</a>

Limit `referer` header's value to 4k.

---

index.src.html

As per conversation with the editors.
Not sure what the ordering of the authors is (seems there is no consistency between W3C specs). Throwing myself up top for now since I have been active recently and am the "newest". Feel free to request otherwise.
***
<a href="https://pr-preview.s3.amazonaws.com/domfarolino/webappsec-referrer-policy/pull/130.html" title="Last updated on Dec 3, 2019, 5:07 PM UTC (c59b31b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/130/65d5c52...domfarolino:c59b31b.html" title="Last updated on Dec 3, 2019, 5:07 PM UTC (c59b31b)">Diff</a>

Add Dominic Farolino as an editor

---

index.html
index.src.html

Other policies that send "full" URLs specify explicitly that the URL should be stripped for use as a referrer. This change alters the description of the no-referrer-when-downgrade referrer policy to be consistent with the other policies in this regard.
***
<a href="https://pr-preview.s3.amazonaws.com/davidvancleve/webappsec-referrer-policy/pull/137.html" title="Last updated on Jun 11, 2020, 9:19 PM UTC (5bc9a80)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/137/fb230a1...davidvancleve:5bc9a80.html" title="Last updated on Jun 11, 2020, 9:19 PM UTC (5bc9a80)">Diff</a>

Have no-referrer-when-downgrade specify stripping the URL as a referrer

---

index.html
index.src.html

This PR fixes #123, and is meant to take over #129, which the author (@yutakahirano) does not have time to work on. This PR addresses my review of #129, as well as takes care of other things. Specifically, in total:
- Stops comparing the origins of a request's [client](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin) and request's [current URL](https://fetch.spec.whatwg.org/#concept-request-current-url) when determining if a request is same-origin or not
- Instead we compare the origins of a request's resolved referrer (its referrer string after "client" has been resolved") and its current URL
- This fixes #123, and is tested
- For the `strict-*` referrer policies, stop comparing request's client's [HTTPS …

Use request's referrer for more things, instead of request's client

---

index.src.html

Fixes https://github.com/w3c/webappsec-referrer-policy/issues/134
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/pull/140.html" title="Last updated on Jun 30, 2020, 9:33 PM UTC (8ddd201)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/140/6d35d84...8ddd201.html" title="Last updated on Jun 30, 2020, 9:33 PM UTC (8ddd201)">Diff</a>

Remove HTML5 note

---

index.html

I noticed that the example in https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-empty-string incorrectly points out that the default referrer policy will resolve to `no-referrer-when-downgrade`. The default now resolves to `strict-origin-when-cross-origin`.
The spec src page was already reflecting this, so I generated this PR by forcing bikeshed to recompile the spec, and voilà.

Rebuild spec to correct a few things

---

index.html
index.src.html

Referrer policy exists as an actual concept on requests, so in the interest of brevity we can just use it directly without using "associated" at the same time, which IMO makes it sound less concrete.
This PR also replaces one instance of "referrer policy" with "<a for=request>referrer policy</a>" in an algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/pull/146.html" title="Last updated on Jan 14, 2021, 6:13 PM UTC (01cd937)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/146/bf0e0fc...01cd937.html" title="Last updated on Jan 14, 2021, 6:13 PM UTC (01cd937)">Diff</a>

No need to use the word "associated" when referring to referrer policy

---

index.src.html

This PR replaces the "Nested browsing context" section with a more general "Referrer Policy Inheritance" section that outlines what I see as the only two places where a referrer policy is ever effectively inherited:
- For requests coming from an iframe srcdoc document, and...
- During `javascript:` navigations
This section was previously wrong because it mentions that we only inherit the referrer policy for documents not created by a response, like srcdoc documents, however srcdoc documents are actually created from a (locally-created) response, so the previous text wasn't quite right. It also leaves out `javascript:` navigations which use locally-created responses as well when the JS evaluates to a string.
This section also used to mention "blob:" URLs, however from looking around in …

Clarify the rare inheritance of referrer policy

---

index.src.html

This fixes a problem in the source that causes non-conforming output (a `dl` element can’t have text nodes).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/pull/151.html" title="Last updated on Mar 12, 2021, 9:23 AM UTC (7685651)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/151/8b762ea...7685651.html" title="Last updated on Mar 12, 2021, 9:23 AM UTC (7685651)">Diff</a>

Editorial: Fix HTML markup conformance error

---

index.src.html

This is a companion change to https://github.com/whatwg/html/pull/6677, which moves referrer policy into the policy container.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 12, 2021, 8:08 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fantosart%2Fwebappsec-referrer-policy%2F73df7303f60edb9ce6cbe2c0907c66f326b74f95%2Findex.src.html&force=1&md-warning=not%20ready)
_If you don't have enough …

Adapt to referrer policy being in policy container

---

.github/workflows/build.yml
index.src.html

Fixes #154
***
<a href="https://pr-preview.s3.amazonaws.com/antosart/webappsec-referrer-policy/pull/157.html" title="Last updated on Nov 10, 2021, 7:45 AM UTC (31fca19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/157/a5fc841...antosart:31fca19.html" title="Last updated on Nov 10, 2021, 7:45 AM UTC (31fca19)">Diff</a>

Fix policy container references in build

---

index.src.html

This closes #153.
- Set url's "password" to an empty string instead of null, since null is not an allowable type per the URL Standard
- Same with "path"
- Adds `for=url` on several `<a>` in this algorithm, since "fragment" was linking to HTML's infrastructure page
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/pull/162.html" title="Last updated on May 24, 2022, 12:26 AM UTC (3321fcd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/162/a02b69a...3321fcd.html" title="Last updated on May 24, 2022, 12:26 AM UTC (3321fcd)">Diff</a>

Fix 'Strip url for use as referrer'

---

index.src.html

As Anne pointed out in https://github.com/w3c/webappsec-referrer-policy/pull/162#issuecomment-1135497605, the `String url for use as referrer` algorithm should set the path to `« the empty string »` so that the URL serializes with a trailing slash.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/pull/163.html" title="Last updated on May 24, 2022, 1:01 PM UTC (b8d0b64)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-referrer-policy/163/2abd67a...b8d0b64.html" title="Last updated on May 24, 2022, 1:01 PM UTC (b8d0b64)">Diff</a>

Fix 'Strip url for use as referrer' to account for trailing slash
